### ISSUE TITLE
Add documentation on how to run a local server for testing

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands_metaserver#15]
I am trying to run a local server for testing, but I get stuck with deploying it:

2. scp wlms over to the server and replace /usr/local/bin/wlms.

I do not have "the server", and I don't know how to get one.

**Comment by SirVer** [comment]
this is just for deploying - the server is widelands.org. 

For local testing you have to provide the metaserver with a user database (there is a commandline switch to get it out of a text file, try `--help`). Then you can ask widelands to use localhost as the metaserver: `widelands --metaserver="127.0.0.1"`. That should work.

**Comment by SirVer** [comment]
Fixed through #16.
