### ISSUE TITLE
IRC users should be listed too

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands_metaserver#3]
Right now it is quite confusing to get messages out of the blue. It would be nice if we had the IRC users listed as well, together with a toggle button in Widelands to disable listing them (so that you can concentrate on gaming). Maybe also filtering IRC traffic when the users are not listed?

**Comment by Notabilis** [comment]
IRC users are displayed in the lobby now. No button to hide them (yet?) but I think it is okay as it is.

Since a possible button would be implemented without modifying the metaserver, I consider this issue done.

**Comment by gunchleoc** [comment]
Great, thanks for taking on the metaserver :)
