### ISSUE TITLE
Users have trouble to join multiplayer lobby

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands_metaserver#34]
Reported on the Froum: https://wl.widelands.org/forum/topic/4300

**Comment by Notabilis** [comment]
Thanks for notifying me, somehow I overlooked the forum thread.
It seems to be related to #1, at least the log also contains the "Message queue full" entries. Not sure why this surfaces now again after all this time. Maybe they restarted the IRC server and this breaks our code? I have to do some testing about that. Also, it does not explain why using a new username seemed to solve it.

Has someone restarted the metaserver to fix it or did that happened by itself?

**Comment by gunchleoc** [comment]
I haven't touched the metaserver. @frankystone?

**Comment by Notabilis** [comment]
I started a pull request that should fix the issue. It was indeed a problem with connection loss to the IRC server as it seems that our code never learned to deal with it.

**Comment by frankystone** [comment]
I din't touched the metaserver also.

Thanks for the fix, Notabilis :-)

**Comment by Notabilis** [comment]
Fix is deployed, hopefully the bug is gone now.
