### ISSUE TITLE
Have equal IRC and in-game names

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands_metaserver#44]
Currently it is not possible to have an in-game name matching the IRC name. The only way to use my IRC name in the game is to logout from IRC. This is especially cumbersome since I registered my name in the forum.

I do understand that duplicated names need to be avoided in multiplayer, but since the users are proxied through the metaserver and irc users are marked as such they should only be renamed if their names is already used in multiplayer.

**Comment by stonerl** [comment]
This line is the culprit I think:
https://github.com/widelands/widelands_metaserver/blob/77bbca98f6f1251771ee76b7128632724a39a53a/wlms/client.go#L519
@Notabilis ?

**Comment by gunchleoc** [comment]
Yes, Notabilis.

**Comment by Notabilis** [comment]
What about chat messages from the "duplicated" user? It wouldn't be possible to figure out whether the IRC user or the Widelands user has written the message. Is this an issue or is this fine for you?

I haven't tested the suggested fix but I think it isn't quite correct. It seems to me as if it would be possible to join the lobby with reserved names that way as long as an IRC user with the name is present.

**Comment by stonerl** [comment]
@Notabilis The fix isn't right.

Regarding the messages. I don't see this as an issue. We Could Prefix the name like this if it is written from IRC. 

```IRC: <username>:```

**Comment by stonerl** [comment]
@Notabilis 
This here would allow admin and registered user to have a name that is used in IRC unregisrted users are still untouched:

```go
		if server.HasClient(c.userName) == nil && (isRegisteredOnServer || !server.UserDb().ContainsName(c.userName)) {
			// Name not in use
			return c.loginDone(server)
		} else if (server.HasClient(c.userName) == server.HasIRCClient(c.userName)) && isRegisteredOnServer {
			// Name is used in IRC but registered on the metaserver
			return c.loginDone(server)
		}
```

**Comment by stonerl** [comment]
The prefixing would look like this:

<img width="912" alt="Screenshot 2019-04-30 at 11 48 28" src="https://user-images.githubusercontent.com/2091312/56953991-f9d25900-6b3d-11e9-8341-14d4a54fe104.png">

~~Shall I add it to the pending PR or open a new one?~~ 

Edit: New picture

**Comment by stonerl** [comment]
I decided to add it to the current PR #47
