### ISSUE TITLE
Admin users cannot host an internet game

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands_metaserver#46]
When a superuser wants to host a game, the connection is severed. I did not find anything in the Widelands code to cause this, so I expect that this is coming fro the metaserver or relay server.

See https://bugs.launchpad.net/widelands/+bug/1826750

**Comment by stonerl** [comment]
Okay I figured what's going on: When a registered user connects this happens on the relay-server:

```
Accepted new host (id=1) with protocol version 1 for game 'Test'.
```

When a SUPERUSER tries to host a game:

```
Disconnecting client (id=0) because NO_HOST
Removing game Test since no host connected to it
```

**Comment by Notabilis** [comment]
This is .. strange. I am not aware of any difference between the users when hosting games, but apparently there is some difference somewhere. I will do some digging in the code.

**Comment by stonerl** [comment]
Found the problem, kind of:

https://github.com/widelands/widelands_metaserver/blob/77bbca98f6f1251771ee76b7128632724a39a53a/wlnr/game.go#L84

When I'm logged in as SUPERUSER the password and game.host Password differ.
```Password: 9d069793174f4084cc4ba32dd31f4855a9996e78 Host-Password:%!(EXTRA string=b52765ec2beab79602644204ff1cdffb980c7557)```

**Comment by stonerl** [comment]
Solved. The wrong hash was calculated because we didn't check for SUPERUSER permission.
