### ISSUE TITLE
Wait a little befor announcing new users

### ISSUE THREAD

**Issue by stonerl** [widelands/widelands_metaserver#52]
I [redesigned](https://code.launchpad.net/~widelands-dev/widelands/bug-1827786-metaserver-login-box-clean-start) the LoginBox and the multiplayer window. 

It is now possible to change login data without entering the lobby. To check the password we log in to the server and immediately log out on success. This can be seen in the IRC-channel though.

Before we announce a client we should put it on a stack and wait for a second or so. When the client logs out within this timespan, it gets removed from the stack without adding it to the list of clients. Otherwise, we remove it from the stack and add it to the client list and send a message into IRC.

**Comment by Notabilis** [comment]
We could solve the issue as you suggested, or we could add a new network command that checks the password without really logging in the user. From a coding perspective, I consider the latter approach "prettier".
However, if we hide successful logins for a few seconds this would also allow users to (really) log in, see who is online and log out again, without spamming messages. This might be desirable, not sure. Which approach do you prefer?

**Comment by gunchleoc** [comment]
Both have merit. The second one is better from a clean code architecture perspective. The first one has the advantage that IRC and the lobby won't get spammed when developers do a really quick log-in-and-leave for testing purposes.

**Comment by stonerl** [comment]
I'll have to second @gunchleoc. The first one can be handled solely on the server side while the second one would also need changes in the game (minor ones though). I'd leave it up to you. Having both would be desirable.

Whatever you think is easier to implement. Should go in first.

**Comment by Notabilis** [comment]
Branches for both approaches are merged and deployed now, so I consider this fixed.
