### ISSUE TITLE
Improve error message for failed login

### ISSUE THREAD

**Issue by gunchleoc** [widelands/widelands_metaserver#53]
Error message "The sent password was incorrect!" - I think it should be called "Wrong password" or "Wrong password, please try again." The user doesn't care about the technical detail that it was sent.

After changing this, make sure that it's localized properly in the Widelands UI too.

**Comment by Notabilis** [comment]
This isn't an issue of the metaserver but of the widelands client. The messages that are displayed to the user are defined in src/network/internet_gaming_messages.cc and src/network/network_gaming_messages.cc. Since they are defined with _("message") they should be localized already.

**Comment by gunchleoc** [comment]
You are right, I'll take care of it over there.

**Comment by Notabilis** [comment]
Thanks!
