### ISSUE TITLE
reconfigure irc channels to libera.chat

### ISSUE THREAD

**Issue by frankystone** [widelands/widelands_metaserver#76]
The channel #widelands has to be moved from freenode to libera.chat.

See: https://www.widelands.org/wiki/ContactPage/

May contact janus on irc://irc.freenode.net/widelands for pointers.

**Comment by frankystone** [comment]
I have tried to configure the metaserver but after restarting wl-metaserver systemctl status says:

~~~~
... Connected to irc.libera.chat:6697 ([2607:5300:205:300::ae0]:6697)
... Error, disconnected: Disconnect Called
~~~~

I guess an account is missing?

**Comment by Notabilis** [comment]
I don't know much about IRC, but from a short test with a local metaserver it seems the configuration file is broken.
The entry `"use_tls"` should actually be `"usetls"`, then it worked in my test (without creating an account earlier).
No idea why this wasn't a problem up to now. Maybe the old IRC server accepts both encrypted and unencrypted connections on the same port?

**Comment by frankystone** [comment]
Great, now it works! Many thanks!

It would be good to have an example of the configuration file though. Will create another issue for this.
